export const CURRENT_YEAR = new Date().getFullYear() - 1

export const TOPICS = {
  android: 'Android',
  cfml: 'ColdFusion/CFML',
  clojure: 'Clojure',
  cpp: 'C++',
  css: 'CSS',
  data: 'Data / AI',
  devops: 'DevOps',
  dotnet: '.NET',
  elixir: 'Elixir',
  elm: 'Elm',
  general: 'General',
  golang: 'Golang',
  graphql: 'GraphQL',
  groovy: 'Groovy',
  ios: 'iOS / Swift',
  iot: 'IoT / Hardware',
  java: 'Java',
  javascript: 'JavaScript',
  kotlin: 'Kotlin',
  leadership: 'Leadership',
  networking: 'Community / Networking',
  php: 'PHP',
  product: 'Product',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  scala: 'Scala',
  security: 'Security',
  testing: 'Testing',
  typescript: 'TypeScript',
  'tech-comm': 'Content strategy',
  ux: 'Design / UX',
}
