export const CURRENT_YEAR = (new Date()).getFullYear() - 1;

export const TOPICS = {
  'tech-comm': 'Content strategy',
  android: 'Android',
  clojure: 'Clojure',
  cpp: 'C++',
  css: 'CSS',
  data: 'Data / AI',
  devops: 'Dev Ops',
  dotnet: '.NET',
  elixir: 'Elixir',
  general: 'General',
  golang: 'Golang',
  graphql: 'GraphQL',
  groovy: 'Groovy',
  ios: 'iOS / Swift',
  java: 'Java',
  javascript: 'JavaScript',
  networking: 'Community / Networking',
  php: 'PHP',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  scala: 'Scala',
  security: 'Security',
  typescript: 'TypeScript',
  elm: 'elm',
  ux: 'Design / UX',
};
