export const validLocations = {
  Argentina: ['Buenos Aires', 'Córdoba'],
  Armenia: ['Yerevan'],
  Australia: [
    'Brisbane',
    'Gold Coast',
    'Melbourne',
    'Newcastle',
    'Perth',
    'Sidney',
    'South Wharf',
    'Sydney',
  ],
  Austria: ['Dornbirn', 'Graz', 'Linz', 'Salzburg', 'Vienna'],
  Bangladesh: ['Dhaka'],
  Belarus: ['Minsk'],
  Belgium: [
    'Antwerp',
    'Brussels',
    'Edegem',
    'Ghent',
    'Leuven',
    'Louvain-La-Neuve',
    'Mechelen',
  ],
  Bolivia: ['Cochabamba'],
  'Bosnia and Herzegovina': ['Banja Luka', 'Sarajevo'],
  Brazil: [
    'Aracaju',
    'Belo Horizonte',
    'Campinas',
    'Chapecó',
    'Feira De Santana',
    'Florianópolis',
    'Fortaleza',
    'Goiânia',
    'Juiz de Fora',
    'Maringá',
    'Porto Alegre',
    'Porto de Galinhas',
    'Recife',
    'Ribeirão Preto',
    'Rio De Janeiro',
    'Salvador',
    'São Paulo',
    'Vitoria',
  ],
  Bulgaria: ['Gabrovo', 'Plovdiv', 'Sofia', 'Varna'],
  Canada: [
    'Banff',
    'Calgary',
    'Edmonton',
    'Gatineau',
    'Halifax',
    'Hamilton',
    'Mississauga',
    'Montebello',
    'Montreal',
    'Ottawa',
    'Quebec',
    'Regina',
    'St. John’s',
    'Toronto',
    'Vancouver',
    'Victoria',
    'Waterloo',
    'Winnipeg',
  ],
  'Cayman Islands': ['George Town'],
  Chile: ['San Antonio', 'Santiago'],
  China: [
    'Beijing',
    'Guangzhou',
    'Hangzhou',
    'Nanjing',
    'Shanghai',
    'Shenzhen',
    'Zhengzhou',
  ],
  Colombia: ['Bogotá', 'Duitama, Boyacá', 'Medellín', 'Tunja'],
  Croatia: [
    'Dubrovnik',
    'Labin',
    'Opatija',
    'Osijek',
    'Rovinj',
    'Sibenik',
    'Split',
    'Zadar',
    'Zagreb',
  ],
  Cuba: ['Holguín', 'Villa Clara'],
  Cyprus: ['Larnaca', 'Paphos'],
  'Czech Republic': ['Prague'],
  Denmark: ['Aarhus', 'Copenhagen', 'Odense'],
  'Dominican Republic': [
    'Playa Dorada',
    'Puerto Plata',
    'Punta Cana',
    'Santiago de los Caballeros',
    'Santo Domingo',
  ],
  Egypt: ['Cairo'],
  Estonia: ['Tallinn'],
  Ethiopia: ['Addis Ababa'],
  Finland: ['Espoo', 'Helsinki', 'Oulu'],
  France: [
    'Anduze',
    'Bordeaux',
    'Bouville',
    'Brest',
    'Grenoble',
    'Lille',
    'Lyon',
    'Marseille',
    'Montpellier',
    'Nantes',
    'Nice',
    'Orléans',
    'Paris',
    'Rennes',
    'Rouen',
    'Sophia-Antipolis',
    'Strasbourg',
    'Toulouse',
  ],
  Georgia: ['Tbilisi'],
  Germany: [
    'Bad Hersfeld',
    'Berlin',
    'Bochum',
    'Bodensee',
    'Bonn',
    'Bremen',
    'Brühl',
    'Chemnitz',
    'Cologne',
    'Darmstadt',
    'Dortmund',
    'Dresden',
    'Düsseldorf',
    'Erlangen',
    'Essen',
    'Frankfurt am Main',
    'Freiburg',
    'Giessen',
    'Hamburg',
    'Hannover',
    'Heidelberg',
    'Karlsruhe',
    'Kiel',
    'Leipzig',
    'Ludwigsburg',
    'Mainz',
    'Mannheim',
    'Munich',
    'Nürburgring',
    'Nürnberg',
    'Ostfildern',
    'Potsdam',
    'Regensburg',
    'Rostock',
    'Rust',
    'Sankt Augustin',
    'St. Leon-Rot',
    'Stuttgart',
    'Tegernsee',
    'Weiden',
    'Wuerzburg',
  ],
  Ghana: ['Accra'],
  Greece: ['Athens', 'Heraklion', 'Thessaloniki'],
  Guatemala: ['Guatemala City'],
  'Hong Kong': ['Hong Kong'],
  Hungary: ['Budapest'],
  Iceland: ['Reykjavík'],
  India: [
    'Ahmedabad',
    'Bangalore',
    'Belagavi',
    'Bengaluru',
    'Chandigarh',
    'Chennai',
    'Coimbatore',
    'Delhi',
    'Goa',
    'Gurgaon',
    'Hyderabad',
    'Jaipur',
    'Kochi',
    'Mumbai',
    'Noida',
    'Pune',
    'Tamil Nadu',
    'Udaipur',
  ],
  Indonesia: ['Bali', 'Jakarta'],
  Iran: ['Tehran'],
  Ireland: ['Athlone', 'Dublin', 'Galway', 'Kilkenny'],
  Israel: [
    'Beersheba',
    'Herzliya',
    'Nasholim',
    'Rishon Lezion, Hamerkaz',
    'Tel Aviv',
  ],
  Italy: [
    'Bergamo',
    'Bologna',
    'Bolzano',
    'Brescia',
    'Castelraimondo',
    'Catania',
    'Cavalese',
    'Desenzano',
    'Desenzano del Garda (BS)',
    'Faenza',
    'Ferrara',
    'Florence',
    'Genova',
    'Levante',
    'Milano',
    'Modena',
    'Napels',
    'Parma',
    'Pescara',
    'Pisa',
    'Rome',
    'Turin',
    'Verona',
    'Volterra',
  ],
  Jamaica: ['Kingston'],
  Japan: [
    'Fukuoka',
    'Koto',
    'Kyoto',
    'Matsue',
    'Mie',
    'Nagano',
    'Takamatsu',
    'Tokyo',
  ],
  Jordan: ['Amman'],
  Kenya: ['Nairobi'],
  Korea: ['Jeju', 'Seoul'],
  Kosovo: ['Pristina', 'Prizren'],
  Latvia: ['Jurmala', 'Riga'],
  Lithuania: ['Vilnius'],
  Luxembourg: ['Esch-sur-Alzette'],
  Malaysia: [
    'Cyberjaya',
    'Iskandar Malaysia',
    'Kuala Lumpur',
    'Penang',
    'Sabah',
  ],
  Malta: ["St Julian's", 'Valletta'],
  Mauritius: ['Moka'],
  Mexico: ['Guadalajara', 'Mazatlán', 'Mexico City', 'Puerto Vallarta'],
  Moldova: ['Chișinău'],
  Morocco: ['Casablanca', 'Taghazout, Agadir'],
  Namibia: ['Windhoek'],
  Nepal: ['Bharatpur', 'Kathmandu'],
  Netherlands: [
    'Amsterdam',
    'Delft',
    'Den Haag',
    'Ede',
    'Eindhoven',
    'Groningen',
    'Hilversum',
    'Rotterdam',
    'Texel',
    'The Hague',
    'Utrecht',
    'Zaandam',
  ],
  'New Zealand': ['Auckland', 'Wellington'],
  Nigeria: ['Lagos'],
  'North Macedonia': ['Skopje'],
  Norway: ['Bergen', 'Kongsberg', 'Larvik', 'Oslo', 'Sandefjord', 'Skien'],
  Panama: ['Panama City'],
  Peru: ['Arequipa', 'Lima'],
  Philippines: [
    'Bohol',
    'Boracay Island',
    'Cebu',
    'Iloilo City',
    'Makati',
    'Manila',
  ],
  Poland: [
    'Gdansk',
    'Gdynia',
    'Katowice',
    'Kraków',
    'Krynica Zdrój',
    'Lodz',
    'Rzeszów',
    'Szczyrk',
    'Warsaw',
    'Wrocław',
    'Zawiercie',
  ],
  Portugal: [
    'Aveiro',
    'Braga',
    'Castelo Branco',
    'Coimbra',
    'Faro',
    'Funchal',
    'Lisbon',
    'Porto',
  ],
  'Puerto Rico': ['Rio Mar'],
  Qatar: ['Doha'],
  Romania: ['Bucharest', 'Cluj-Napoca', 'Iasi', 'Timisoara'],
  Russia: ['Moscow', 'Novosibirsk', 'Saint Petersburg', 'Yekaterinburg'],
  'Saudi Arabia': ['Riyadh'],
  Scotland: ['Edinburgh', 'Glasgow', 'Perthshire'],
  Serbia: ['Belgrade', 'Novi Sad'],
  Singapore: ['Singapore'],
  Slovakia: ['Bratislava', 'Jasna', 'Nitra', 'Tatras'],
  Slovenia: ['Laško', 'Ljubljana', 'Portorož'],
  'South Africa': ['Cape Town', 'Johannesburg'],
  'South Korea': ['Busan', 'Incheon', 'Pohang', 'Seoul', 'Suwon'],
  Spain: [
    'A Coruña',
    'Alicante',
    'Barcelona',
    'Bilbao',
    'Canarias',
    'Cáceres',
    'Cádiz',
    'Gran Canaria',
    'Ibiza',
    'Logroño',
    'Madrid',
    'Malaga',
    'Marbella',
    'Sitges, Barcelona',
    'Tenerife',
    'Valencia',
    'Vigo',
    'Zaragoza',
  ],
  Sweden: ['Gothenburg', 'Helsingborg', 'Kalmar', 'Malmö', 'Stockholm'],
  Switzerland: [
    'Basel',
    'Bern',
    'Buchs',
    'Crans-Montana',
    'Fribourg',
    'Geneva',
    'Lausanne',
    'Lugano',
    'Nottwil',
    'Rapperswil-Jona',
    'Zurich',
  ],
  Taiwan: ['Taipei'],
  Tanzania: ['Dar es Salaam'],
  Thailand: ['Bangkok', 'Nakhon Pathom'],
  Turkey: ['Istanbul'],
  'U.K.': [
    'Aberystwyth',
    'Bath',
    'Belfast',
    'Birmingham',
    'Bournemouth',
    'Brighton',
    'Bristol',
    'Cambridge',
    'Cardiff',
    'Chester',
    'Daventry',
    'Edinburgh',
    'Exeter',
    'Falmouth, Cornwall',
    'Folkestone',
    'Leeds',
    'London',
    'Manchester',
    'Middlesbrough',
    'Newcastle',
    'Newcastle-Upon-Tyne',
    'Newquay',
    'Norwich',
    'Oxford',
    'Sheffield',
    'York',
  ],
  'U.S.A.': [
    'Alexandria, VA',
    'Anaheim, CA',
    'Arlington, VA',
    'Asheville, NC',
    'Aspen, CO',
    'Atlanta, GA',
    'Atlantic Beach, FL',
    'Augusta, GA',
    'Aurora, CO',
    'Austin, TX',
    'Baltimore, MD',
    'Bandera, TX',
    'Beckenridge, CO',
    'Bellevue, WA',
    'Bend, OR',
    'Bentonville, AR',
    'Berkeley, CA',
    'Birmingham, AL',
    'Boise, ID',
    'Boston, MA',
    'Boulder, CO',
    'Bozeman, MT',
    'Bremerton, WA',
    'Brooklyn, NY',
    'Broomfield, CO',
    'Buffalo, NY',
    'Burlingame, CA',
    'Burlington, VT',
    'Cambridge, MA',
    'Cape Canaveral, FL',
    'Carlsbad, CA',
    'Carmel, IN',
    'Charleston, SC',
    'Charlotte, NC',
    'Chattanooga, TN',
    'Chicago, IL',
    'Cincinnati, OH',
    'Clear Water, FL',
    'Clearwater, FL',
    'Cleveland, OH',
    'Columbia, SC',
    'Columbus, GA',
    'Columbus, OH',
    'Cupertino, CA',
    'Dallas, TX',
    'Dayton, OH',
    'Denver, CO',
    'Des Moines, IA',
    'Detroit, MI',
    'Durham, NC',
    'East Point, GA',
    'Fort Lauderdale, FL',
    'Fort Worth, TX',
    'Galveston, TX',
    'Grand Rapids, MI',
    'Grants Pass, OR',
    'Grapevine, TX',
    'Greenville, SC',
    'Half Moon Bay, CA',
    'Hartford, CT',
    'Henderson, NV',
    'Hollywood, FL',
    'Honolulu, HI',
    'Houston, TX',
    'Huntsville, AL',
    'Indianapolis, IN',
    'Jackson, MS',
    'Jacksonville Beach, FL',
    'Kansas City, KS',
    'Kansas City, MO',
    'Knoxville, TN',
    'La Jolla, CA',
    'Lahaina, HI',
    'Las Vegas, NV',
    'Lincoln, NE',
    'Little Rock, AR',
    'Long Beach, CA',
    'Los Angeles, CA',
    'Louisville, KY',
    'Madison, WI',
    'McLean, VA',
    'Mesa, AZ',
    'Miami, FL',
    'Milwaukee, WI',
    'Minneapolis, MN',
    'Modesto, CA',
    'Mountain View, CA',
    'Nashville, TN',
    'New Haven, CT',
    'New Orleans, LA',
    'New York, NY',
    'Newark, CA',
    'Oakland, CA',
    'Oklahoma City, OK',
    'Omaha, NE',
    'Orlando, FL',
    'Oxon Hill, MD',
    'Palm Springs, CA',
    'Palo Alto, CA',
    'Park City, UT',
    'Pasadena, CA',
    'Philadelphia, PA',
    'Phoenix, AZ',
    'Pittsburgh, PA',
    'Pocono Manor, PA',
    'Port Canaveral, FL',
    'Portland, OR',
    'Prince William Forest Park, VA',
    'Princeton, NJ',
    'Providence, RI',
    'Raleigh, NC',
    'Raleigh-Durham, NC',
    'Redmond, WA',
    'Redwood City, CA',
    'Reston, VA',
    'Richardson, TX',
    'Richmond, VA',
    'Rochester, NY',
    'Rockville, MD',
    'Round Rock, TX',
    'Saint Paul, MN',
    'Salt Lake City, UT',
    'San Antonio, TX',
    'San Diego, CA',
    'San Francisco, CA',
    'San Jose, CA',
    'San Mateo, CA',
    'Sandusky, OH',
    'Sandy, UT',
    'Santa Clara, CA',
    'Scottsdale, AZ',
    'Seattle, WA',
    'Sparks, NV',
    'St. Augustine, FL',
    'St. Charles, MO',
    'St. Louis, MO',
    'St. Petersburg, FL',
    'Stamford, CT',
    'Stanford, CA',
    'Sunnyvale, CA',
    'Tampa Bay, FL',
    'Tampa, FL',
    'Tempe, AZ',
    'Texas, IL',
    'Tulsa, OK',
    'Virginia Beach, VA',
    'Walker Creek Ranch, CA',
    'Wall, NJ',
    'Washington, DC',
    'Waterloo, ON',
    'Wisconsin Dells, WI',
  ],
  Ukraine: ['Chernivtsi', 'Kharkiv', 'Kyiv', 'Lviv', 'Odessa', 'Vinnytsia'],
  'United Arab Emirates': ['Abu Dhabi', 'Dubai'],
  Uruguay: ['Montevideo'],
  Vietnam: ['Ho Chi Minh City'],
}
